disabled_rules: # rule identifiers to exclude from running
  - nesting
  - type_name
  - trailing_whitespace
  - line_length:
        warning: 90
  - force_cast
  - line_length
  - identifier_name
  - function_body_length
  - type_body_length
  - void_function_in_ternary
  
file_length:
  warning: 400
  error: 500
line_length:
  warning: 90
function_body_length: 20
type_name:
  min_length: 1
  max_length: 40
  
